name: ci

# Run this workflow on every PR into main, and every push to main
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Get your repo code
      - uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Step 3: Install dependencies
      - run: npm ci

      # Step 4: Run linters (if package.json has a "lint" script)
      - run: npm run lint --if-present

      # Step 5: Build the project (catches type errors, syntax errors, etc.)
      - run: npm run build
